[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["pricing/pricing.json"]

[build.environment]
  NODE_VERSION = "20.12.2"

[functions."push-chunk-cleanup"]
  schedule = "@daily"

[functions."push-job-retry"]
  schedule = "*/5 * * * *"


[functions."gh-job-retry"]
  schedule = "*/5 * * * *"

[functions."gh-chunk-cleanup"]
  schedule = "@daily"

[functions."monitor-archive-prune"]
  schedule = "@daily"
